import type { TechDetectionRule } from "@/lib/tech-stack/types";

export const techDetectionRules: TechDetectionRule[] = [
  {
    id: "nextjs-header",
    technology: "Next.js",
    category: "Framework / Runtime",
    confidence: "high",
    matcher: { type: "header-contains", header: "x-powered-by", value: "Next.js" },
  },
  {
    id: "nextjs-html",
    technology: "Next.js",
    category: "Framework / Runtime",
    confidence: "medium",
    matcher: { type: "html-regex", pattern: "__NEXT_DATA__|/_next/" },
  },
  {
    id: "react-html",
    technology: "React",
    category: "Frontend / UI",
    confidence: "medium",
    matcher: { type: "html-regex", pattern: "data-reactroot|react-root" },
  },
  {
    id: "vue-html",
    technology: "Vue.js",
    category: "Frontend / UI",
    confidence: "medium",
    matcher: { type: "html-regex", pattern: "__vue__|data-v-" },
  },
  {
    id: "angular-html",
    technology: "Angular",
    category: "Framework / Runtime",
    confidence: "medium",
    matcher: { type: "html-regex", pattern: "ng-version|_ngcontent-" },
  },
  {
    id: "wordpress-meta",
    technology: "WordPress",
    category: "CMS / Metadata",
    confidence: "high",
    matcher: { type: "meta-generator-contains", value: "wordpress" },
  },
  {
    id: "wordpress-assets",
    technology: "WordPress",
    category: "CMS / Metadata",
    confidence: "medium",
    matcher: { type: "html-regex", pattern: "wp-content|wp-includes" },
  },
  {
    id: "shopify-assets",
    technology: "Shopify",
    category: "CMS / Metadata",
    confidence: "high",
    matcher: { type: "html-regex", pattern: "cdn\\.shopify\\.com|shopify-payment-button" },
  },
  {
    id: "webflow-assets",
    technology: "Webflow",
    category: "CMS / Metadata",
    confidence: "high",
    matcher: { type: "html-regex", pattern: "webflow\\.js|data-wf-page|data-wf-site" },
  },
  {
    id: "gtm-script",
    technology: "Google Tag Manager",
    category: "Analytics / Tag Manager",
    confidence: "high",
    matcher: { type: "script-src-regex", pattern: "googletagmanager\\.com/(gtm|gtag)\\.js" },
  },
  {
    id: "ga-cookie",
    technology: "Google Analytics",
    category: "Analytics / Tag Manager",
    confidence: "low",
    matcher: { type: "cookie-name", cookieName: "_ga" },
  },
  {
    id: "segment-script",
    technology: "Segment",
    category: "Analytics / Tag Manager",
    confidence: "high",
    matcher: { type: "script-src-regex", pattern: "cdn\\.segment\\.com" },
  },
  {
    id: "hubspot-cookie",
    technology: "HubSpot",
    category: "Analytics / Tag Manager",
    confidence: "medium",
    matcher: { type: "cookie-name", cookieName: "hubspotutk" },
  },
  {
    id: "stripe-script",
    technology: "Stripe",
    category: "Payments / Widgets",
    confidence: "high",
    matcher: { type: "script-src-regex", pattern: "js\\.stripe\\.com" },
  },
  {
    id: "paypal-script",
    technology: "PayPal",
    category: "Payments / Widgets",
    confidence: "high",
    matcher: { type: "script-src-regex", pattern: "paypal\\.com/sdk/js" },
  },
  {
    id: "cloudflare-combined",
    technology: "Cloudflare",
    category: "CDN / WAF",
    confidence: "high",
    matcher: {
      type: "combined",
      matchers: [
        { type: "header-contains", header: "server", value: "cloudflare" },
        { type: "dns-pattern", recordType: "ns", pattern: "cloudflare" },
      ],
    },
  },
  {
    id: "akamai-dns",
    technology: "Akamai",
    category: "CDN / WAF",
    confidence: "medium",
    matcher: { type: "dns-pattern", recordType: "cname", pattern: "akamai" },
  },
  {
    id: "vercel-cname",
    technology: "Vercel",
    category: "Hosting / Cloud",
    confidence: "high",
    matcher: { type: "dns-pattern", recordType: "cname", pattern: "vercel-dns\\.com" },
  },
  {
    id: "netlify-header",
    technology: "Netlify",
    category: "Hosting / Cloud",
    confidence: "medium",
    matcher: { type: "header-contains", header: "server", value: "Netlify" },
  },
  {
    id: "aws-amplify-html",
    technology: "AWS Amplify",
    category: "Hosting / Cloud",
    confidence: "medium",
    matcher: { type: "html-regex", pattern: "amplifyapp\\.com" },
  },
  {
    id: "google-workspace-mx",
    technology: "Google Workspace",
    category: "DNS / Mail / Security",
    confidence: "medium",
    matcher: { type: "dns-pattern", recordType: "mx", pattern: "google\\.com" },
  },
  {
    id: "microsoft-365-mx",
    technology: "Microsoft 365",
    category: "DNS / Mail / Security",
    confidence: "medium",
    matcher: { type: "dns-pattern", recordType: "mx", pattern: "outlook\\.com" },
  },
  {
    id: "spf-record",
    technology: "SPF",
    category: "DNS / Mail / Security",
    confidence: "low",
    matcher: { type: "dns-pattern", recordType: "txt", pattern: "^v=spf1" },
  },
  {
    id: "csp-enabled",
    technology: "Content Security Policy",
    category: "DNS / Mail / Security",
    confidence: "low",
    matcher: { type: "security-header-present", header: "content-security-policy" },
  },
  {
    id: "hsts-enabled",
    technology: "HTTP Strict Transport Security",
    category: "DNS / Mail / Security",
    confidence: "low",
    matcher: { type: "security-header-present", header: "strict-transport-security" },
  },
  {
    id: "google-fonts-link",
    technology: "Google Fonts",
    category: "Frontend / UI",
    confidence: "high",
    matcher: { type: "link-href-regex", pattern: "fonts\\.googleapis\\.com|fonts\\.gstatic\\.com" },
  },
  {
    id: "font-awesome-link",
    technology: "Font Awesome",
    category: "Frontend / UI",
    confidence: "medium",
    matcher: { type: "link-href-regex", pattern: "font-awesome|cdnjs\\.cloudflare\\.com/ajax/libs/font-awesome" },
  },
  {
    id: "react-core-script",
    technology: "React",
    category: "Frontend / UI",
    confidence: "high",
    matcher: { type: "script-src-regex", pattern: "react-core|react-dom|react\\." },
  },
  {
    id: "hotjar-script",
    technology: "Hotjar",
    category: "Analytics / Tag Manager",
    confidence: "high",
    matcher: { type: "script-src-regex", pattern: "static\\.hotjar\\.com" },
  },
  {
    id: "youtube-player",
    technology: "YouTube",
    category: "Frontend / UI",
    confidence: "high",
    matcher: {
      type: "html-regex",
      pattern: "ytmainappweb|android-app://com\\.google\\.android\\.youtube|og:title[\"\\'] content=[\"\\']YouTube",
    },
  },
  {
    id: "polymer-runtime",
    technology: "Polymer",
    category: "Framework / Runtime",
    confidence: "high",
    matcher: {
      type: "html-regex",
      pattern: "window\\[\"Polymer\"\\]|Polymer\\.Base",
    },
  },
  {
    id: "redux-runtime",
    technology: "Redux",
    category: "Frontend / UI",
    confidence: "medium",
    matcher: {
      type: "html-regex",
      pattern: "redux",
    },
  },
  {
    id: "pwa-manifest",
    technology: "PWA",
    category: "Framework / Runtime",
    confidence: "high",
    matcher: {
      type: "link-href-regex",
      pattern: "manifest\\.webmanifest",
    },
  },
  {
    id: "open-graph-tags",
    technology: "Open Graph",
    category: "CMS / Metadata",
    confidence: "high",
    matcher: {
      type: "html-regex",
      pattern: "property=[\"\\']og:",
    },
  },
  {
    id: "http3-alt-svc",
    technology: "HTTP/3",
    category: "Framework / Runtime",
    confidence: "high",
    matcher: {
      type: "header-contains",
      header: "alt-svc",
      value: "h3=",
    },
  },
  {
    id: "turbo-headers",
    technology: "Turbo",
    category: "Framework / Runtime",
    confidence: "medium",
    matcher: {
      type: "header-contains",
      header: "vary",
      value: "Turbo-Visit",
    },
  },
  {
    id: "cloudfront-header",
    technology: "Amazon CloudFront",
    category: "CDN / WAF",
    confidence: "high",
    matcher: { type: "header-contains", header: "via", value: "cloudfront" },
  },
  {
    id: "fastly-header",
    technology: "Fastly",
    category: "CDN / WAF",
    confidence: "medium",
    matcher: { type: "header-contains", header: "x-served-by", value: "cache-" },
  },
  {
    id: "imperva-header",
    technology: "Imperva",
    category: "CDN / WAF",
    confidence: "medium",
    matcher: { type: "header-contains", header: "x-iinfo", value: "-" },
  },
  {
    id: "amazon-s3-link",
    technology: "Amazon S3",
    category: "Hosting / Cloud",
    confidence: "medium",
    matcher: {
      type: "link-href-regex",
      pattern: "s3\\.amazonaws\\.com|github-cloud\\.s3\\.amazonaws\\.com",
    },
  },
  {
    id: "vercel-hosting-header",
    technology: "Vercel",
    category: "Hosting / Cloud",
    confidence: "high",
    matcher: { type: "header-contains", header: "x-vercel-id", value: "::" },
  },
  {
    id: "nuxt-framework",
    technology: "Nuxt.js",
    category: "Framework / Runtime",
    confidence: "high",
    matcher: { type: "html-regex", pattern: "__NUXT__|__nuxt__" },
  },
  {
    id: "meta-pixel",
    technology: "Meta Pixel",
    category: "Analytics / Tag Manager",
    confidence: "high",
    matcher: { type: "script-src-regex", pattern: "connect\\.facebook\\.net/en_US/fbevents\\.js" },
  },
  {
    id: "woocommerce-shop",
    technology: "WooCommerce",
    category: "CMS / Metadata",
    confidence: "high",
    matcher: { type: "html-regex", pattern: "woocommerce|WooCommerce" },
  },
  {
    id: "magento-platform",
    technology: "Magento",
    category: "CMS / Metadata",
    confidence: "medium",
    matcher: { type: "html-regex", pattern: "Mage\\.|Magento" },
  },
  {
    id: "expressjs-server",
    technology: "Express.js",
    category: "Framework / Runtime",
    confidence: "medium",
    matcher: { type: "header-contains", header: "x-powered-by", value: "Express" },
  },
  {
    id: "php-runtime",
    technology: "PHP",
    category: "Framework / Runtime",
    confidence: "high",
    matcher: {
      type: "combined",
      matchers: [
        { type: "header-contains", header: "x-powered-by", value: "PHP" },
        { type: "cookie-name", cookieName: "PHPSESSID" },
      ],
    },
  },
  {
    id: "laravel-framework",
    technology: "Laravel",
    category: "Framework / Runtime",
    confidence: "high",
    matcher: { type: "cookie-name", cookieName: "XSRF-TOKEN" },
  },
  {
    id: "bootstrap-framework",
    technology: "Bootstrap",
    category: "Frontend / UI",
    confidence: "high",
    matcher: { type: "link-href-regex", pattern: "bootstrap\\.min\\.css|cdn\\.jsdelivr\\.net.*bootstrap" },
  },
  {
    id: "aws-infrastructure",
    technology: "Amazon Web Services",
    category: "Hosting / Cloud",
    confidence: "medium",
    matcher: { type: "dns-pattern", recordType: "ns", pattern: "awsdns" },
  },
];
